CREATE TABLE hosts (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  protocol TEXT NOT NULL CHECK (protocol IN ('ftp','ftps_explicit','ftps_implicit','sftp','rsync','scp')),
  host TEXT NOT NULL,
  port INTEGER NOT NULL,
  username TEXT NOT NULL,
  secret_enc BLOB,
  auth_kind TEXT NOT NULL DEFAULT 'password' CHECK (auth_kind IN ('password','key')),
  tls_accept_self_signed INTEGER NOT NULL DEFAULT 0,
  host_keys TEXT,
  host_key_sha256 TEXT,
  max_connections INTEGER NOT NULL DEFAULT 4 CHECK (max_connections BETWEEN 1 AND 32),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE jobs (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  host_id INTEGER NOT NULL REFERENCES hosts(id),
  enabled INTEGER NOT NULL DEFAULT 1,
  remote_path TEXT NOT NULL,
  local_path TEXT NOT NULL,
  mode TEXT NOT NULL DEFAULT 'copy_new' CHECK (mode IN ('copy_new','mirror')),
  unit_mode TEXT NOT NULL DEFAULT 'top_dir' CHECK (unit_mode IN ('file','top_dir')),
  after_sync TEXT NOT NULL DEFAULT 'keep' CHECK (after_sync IN ('keep','delete','delete_after_days','move')),
  after_days INTEGER,
  move_to TEXT,
  verify TEXT NOT NULL DEFAULT 'size' CHECK (verify IN ('size','checksum')),
  settle_seconds INTEGER NOT NULL DEFAULT 300,
  min_age_seconds INTEGER NOT NULL DEFAULT 0,
  min_size INTEGER,
  max_size INTEGER,
  include_globs TEXT NOT NULL DEFAULT '[]',
  exclude_globs TEXT NOT NULL DEFAULT '[]',
  trust_mtime INTEGER NOT NULL DEFAULT 0,
  rerun_pending INTEGER NOT NULL DEFAULT 0,
  bwlimit_bps INTEGER,
  parallel_files INTEGER NOT NULL DEFAULT 2 CHECK (parallel_files BETWEEN 1 AND 16),
  range_streams INTEGER NOT NULL DEFAULT 4 CHECK (range_streams BETWEEN 1 AND 8),
  retries INTEGER NOT NULL DEFAULT 3 CHECK (retries BETWEEN 0 AND 10),
  min_free_bytes INTEGER,
  schedule_kind TEXT NOT NULL DEFAULT 'manual' CHECK (schedule_kind IN ('cron','interval','manual')),
  schedule_expr TEXT,
  changed_policy TEXT NOT NULL DEFAULT 'skip' CHECK (changed_policy IN ('skip','resync')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
